[workspace]
members = [
    "crates/types",
    "crates/macros",
    "crates/interface",
    "crates/runtime/ext/http",
    "crates/runtime",
    "crates/server",
    "crates/cli",
    "crates/example",
]