[workspace]
members = [
    "crates/types",
    "crates/sdk/macros",
    "crates/sdk",
    "crates/extensions/http-outbound",
    "crates/runtime",
    "crates/server",
    "crates/cli",
    "crates/example",
]